"""Planner node — LLM-driven experiment configuration selection."""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path

from inference_agent.models import (
    AgentConfig,
    EngineType,
    ExperimentConfig,
    ExperimentSummary,
    HardwareProfile,
    OptimizationGoal,
    PlannerOutput,
)
from inference_agent.state import AgentState
from inference_agent.utils.llm import structured_output

logger = logging.getLogger(__name__)

# Curated CLI flag references injected into the planner prompt.
# Generated by scripts/llmify_engine_docs.py; checked into the repo.
_ENGINE_DOCS_DIR = Path(__file__).resolve().parents[3] / "engine-docs"
_CURATED_DOCS = {
    EngineType.VLLM: _ENGINE_DOCS_DIR / "vllm" / "cli_params.curated.md",
    EngineType.SGLANG: _ENGINE_DOCS_DIR / "sglang" / "cli_params.curated.md",
}


@lru_cache(maxsize=4)
def _load_curated_docs(engine: EngineType) -> str:
    """Load the curated CLI-flag reference for the given engine, or return empty
    string if missing (e.g., docs not regenerated)."""
    path = _CURATED_DOCS.get(engine)
    if path is None or not path.exists():
        logger.warning("Curated docs missing for %s at %s", engine.value, path)
        return ""
    return path.read_text(encoding="utf-8")

_PROMPT_HEADER = """\
You are an expert LLM inference optimization engineer. Your job is to choose \
the next configuration to benchmark for an LLM inference engine running on a GPU server.

## Hardware Profile
{hardware_json}

## Engine for This Experiment
{engine_instruction}

## Optimization Goal
{optimization_goal}
{baseline_block}
## Top Results from Prior Runs (same hardware + model, loaded from DB)
These are the best already-measured configurations on this exact hardware/model from \
previous sessions. Treat them as a strong starting point: prefer iterating ON them \
(adjusting up to {max_params_per_step} parameter(s) at a time) over re-running a \
generic baseline. Skip Rule 1 \
(baseline) when prior tops exist — you already have a baseline.
{loaded_top_history_json}

## Previous Experiments This Session (most recent last)
{history_json}

## Best Results So Far
- Best AGENTIC (primary): max_viable_agents={best_agentic_c} \
(config: {best_agentic_id}, agentic_tpot_p95={best_agentic_tpot:.1f}ms, \
agentic_throughput={best_agentic_tp:.1f} tok/s)
- Best latency (TTFT p95): {best_latency:.1f} ms (config: {best_latency_id})
- Best balanced (max agentic c under TTFT≤{latency_threshold}ms): \
agents={best_balanced_tp:.0f}, ttft={best_balanced_lat:.1f}ms \
(config: {best_balanced_id})
- (Informational only — NOT a goal) Best raw throughput: \
{best_throughput:.1f} tok/s (config: {best_throughput_id}). c=256/p=512 wins \
here do NOT count as leadership — agentic concurrency is what we are \
optimizing for.

## Experiment Count
{exp_count} / {max_experiments}

## Rules
0. QUANTIZATION IS FIXED for this run at: {fixed_quantization}. It is applied \
to every experiment by the agent — DO NOT try to vary it, do not pass any \
`--quantization` flag via extra_engine_args, and do not reason about which \
quantization method to use. Treat it as part of the hardware/model setup.
0a. MAX_MODEL_LEN IS FIXED for this run at: {fixed_max_model_len}. It is \
applied to every experiment by the agent — DO NOT try to vary it, do not \
pass `--max-model-len` / `--context-length` via extra_engine_args, and do \
NOT include max_model_len in your rationale as a tunable knob. Treat it as \
a hardware/product constraint. The schema field `max_model_len` will be \
overridden with the fixed value regardless of what you emit; you may emit \
any plausible value to satisfy the JSON schema.
1. For BASELINES: use default params — no speculative decoding, \
kv_cache_dtype=auto, scheduling_policy=fcfs. ENABLE prefix caching (it is \
mandatory under the agentic goal — see Rule 3a — and harmless elsewhere). \
SKIP THIS RULE ENTIRELY when a `## BASELINE — operator anchor` block is \
present above: that measured config IS the baseline, you must iterate on it \
(changing at most {max_params_per_step} parameter(s) at a time), NOT emit a \
fresh generic baseline.
2. After baselines, analyze trends and improve based on the optimization goal. \
Change AT MOST {max_params_per_step} configuration parameter(s) per experiment \
relative to your starting point (the baseline anchor or the prior top result), \
and NAME each change plus its expected impact in your rationale. Fewer, isolated \
deltas make it clear which knob moved the metric; only widen the change set when \
trends have stalled.
3. PRIMARY GOAL — "optimize_agentic" (maximize parallel agents under SLO). \
The headline metric is `agentic.max_viable_concurrency`. Levers, in order \
of expected impact:
   - **Increase KV budget.** vLLM: `gpu_memory_utilization` 0.88→0.92→0.95 \
(watch OOM). SGLang: `mem_fraction_static` 0.88→0.93. More KV → more \
long-context sessions in parallel.
   - **`enable_prefix_caching` MUST be true.** The benchmark uses a shared \
prefix across all sessions; without prefix caching it is re-prefilled per \
session and concurrency collapses. The validator will reject configs that \
disable it under the agentic goal.
   - **`max_model_len` ≤ realistic agent context.** Do NOT pick 131072/262144 \
under the agentic goal — that just reserves KV budget for a context window \
nobody uses. Choose the smallest bucket from {{16384, 32768, 65536}} that \
still fits shared_prefix + unique + turns × (out + tool). The validator \
warns when oversized.
   - **`chunked_prefill_size` smaller** (vLLM `--max-num-batched-tokens` ~4096-8192, \
SGLang `chunked_prefill_size=4096`) — fairer scheduling when many sessions \
share heavy prefill bursts.
   - **`max_running_requests` (SGLang) / `max_num_seqs` (vLLM) ≈ 2-4× the \
expected viable concurrency** — generous enough to absorb bursts without \
starving KV. Do NOT push these to 256/288 (those are throughput-shaped \
configurations and waste KV under the agentic SLO).
   - **Speculative decoding is usually NEUTRAL or NEGATIVE under agentic.** \
Small effective batch (c=8..48) plus long context drops accept-rate; raw \
overhead can dominate. Try it only after exhausting the levers above, and \
prefer self-speculation (NEXTN / mtp) when mtp_num_layers > 0.
3a. THINGS THAT HURT AGENTIC AND SHOULD BE AVOIDED unless explicitly testing \
them: enable_chunked_prefill=false (slows multi-session prefill fairness); \
prefix_caching=false (kills shared-prefix reuse — VALIDATOR REJECTS); large \
max_model_len like 131072+ when shared+unique+turns*out fits in <65536.
4. If goal is "optimize_latency": focus on TP, enforce_eager, lower batch \
sizes. Latency rank uses the cold-start TTFT p95 at c=1; agentic SLO does \
not apply here.
5. If goal is "optimize_balanced": find configs where TTFT p95 < {latency_threshold} ms \
AND max_viable_agentic_concurrency is maximized. NOT raw throughput.
6. If goal is "explore": try something new — speculative decoding, different \
max_model_len, attention backends. Still respect Rule 3a (prefix caching on; \
max_model_len ≤ ~2× agentic workload budget). Explore is an axis SEARCH, \
not a license to revert to throughput-shaped configs (`max_num_seqs`/ \
`max_running_requests` ≥ 256, `max_model_len` ≥ 131072 with no agentic \
justification). The validator will reject those under optimize_agentic; \
under explore they still waste a slot.
7. SPECULATIVE DECODING is a first-class lever — actively probe it once a stable baseline exists, \
do NOT treat it as a last resort. Sweep across algorithms (vLLM: ngram, eagle, eagle3, medusa, mlp_speculator; \
SGLang: NEXTN, EAGLE, EAGLE3) AND across `speculative_num_steps` (try at least 3, 5, 8) AND across \
draft model choices when applicable. A single failed or slow speculative run is NOT enough to abandon the \
whole family — vary the algorithm and num_steps before concluding speculative decoding is unhelpful for \
this model/hardware. For latency-oriented goals it is especially important to exhaust speculative variants. \
The auto-disable safeguard only kicks in after 3 consecutive engine failures, so you have headroom to explore.
7a. NATIVE MTP HEADS: hardware.mtp_num_layers reports how many built-in Multi-Token Prediction heads \
the model ships with (Qwen3.5-MoE: typically 1, DeepSeek-V3: typically 1-3). When mtp_num_layers > 0:
   - The model self-speculates — for SGLang use `speculative_algorithm="NEXTN"` (or "EAGLE3") \
     WITHOUT `speculative_draft_model`; for vLLM try `speculative_algorithm="mtp"` or "eagle3" \
     similarly without an external draft. This is the cheapest, fastest speculative experiment to run \
     and should be among your FIRST speculative attempts.
   - Cap `speculative_num_steps` at mtp_num_layers — predicting more tokens than there are heads \
     wastes a slot and the validator will reject it.
   - When mtp_num_layers == 0: NEXTN is unavailable; speculative decoding requires an external \
     `speculative_draft_model` (a real, smaller HuggingFace model from the same family). The agent \
     prefetches the draft model into the host HF cache before launching the container — if the repo \
     ID is wrong / non-existent, the experiment fails fast with `prefetch_failed` (not a 20-minute \
     container hang). Pick draft models you are confident exist (same tokenizer/vocab family as the \
     main model); a `prefetch_failed` in history means that exact draft ID is unusable, do not retry it.
8. Never repeat an exact configuration that was already tested.
9. max_model_len: choose ONE of {{16384, 32768, 65536, 131072, 262144}}, capped at {model_max_context}. \
The OBJECTIVE is to maximize performance at the LARGEST context that fits VRAM. \
Estimate available KV budget = total_vram - model_weight_bytes - ~10% headroom, then pick the \
largest power-of-2 that plausibly fits. Halve ONLY on a confirmed OOM — do NOT anchor at 32768 \
by default; that is a floor, not a starting point.
10. tensor_parallel_size must divide evenly into {gpu_count} GPUs.
11. CRITICAL: If a feature (attention backend, scheduling policy, etc.) consistently gives WORSE results than \
baseline ACROSS multiple variants, STOP using it. For speculative decoding specifically: only abandon \
after trying at least 2 different algorithms AND 2 different `speculative_num_steps` values — a single \
slow run is not a verdict on the whole family.
12. If a previous experiment FAILED, read the error, fix the root cause, do NOT repeat the same config.
"""

_VLLM_SECTION = """
## vLLM Best Practices
You are configuring a **vLLM** experiment. The full curated CLI flag reference is \
attached below; here are key principles:
- Chunked prefill + prefix caching work well together for throughput.
- enforce_eager=true can reduce latency for small batches but hurts throughput.
- Higher gpu_memory_utilization (0.95) allows more KV cache but risks OOM.
- scheduling_policy: ONLY "fcfs" (default) or "priority". Do NOT use "lpm".
- Speculative decoding is a HIGH-PRIORITY exploration lever — once you have a clean \
  baseline, actively try `speculative_algorithm` ∈ {{ngram, eagle, eagle3, medusa, \
  mlp_speculator, mtp}} and sweep `speculative_num_steps` ∈ {{3, 5, 8}}. \
  Draft-model rules:
    * `ngram` — no draft model needed (uses prompt n-grams). Cheapest experiment, \
      especially good for repetitive / structured prompts (agent traces, JSON).
    * `mtp`, `eagle3` — when hardware.mtp_num_layers > 0 they self-speculate using \
      the model's own MTP heads, no `speculative_draft_model` required. When \
      mtp_num_layers == 0 they DO require a real HuggingFace `speculative_draft_model`.
    * `eagle`, `medusa`, `mlp_speculator` — always require a real HuggingFace \
      `speculative_draft_model`.
  Vary the algorithm and num_steps before concluding speculative decoding is a dead end \
  for this model.

Leave SGLang-specific fields at defaults: mem_fraction_static=null, \
max_running_requests=null, max_prefill_tokens=null, chunked_prefill_size=null, \
num_continuous_decode_steps=1, dp_size=null.
"""

_SGLANG_SECTION = """
## SGLang Best Practices
You are configuring an **SGLang** experiment. The full curated CLI flag reference is \
attached below; here are key principles:
- Radix cache (prefix caching) ON by default — lpm scheduling benefits from it.
- num_continuous_decode_steps > 1 reduces scheduling overhead.
- scheduling_policy: "fcfs" (default) or "lpm". lpm benefits from prefix caching.
- Speculative decoding (NEXTN / EAGLE / EAGLE3) is a HIGH-PRIORITY exploration lever — \
  after a clean baseline, ACTIVELY sweep `speculative_algorithm` ∈ {{NEXTN, EAGLE, EAGLE3}} \
  AND `speculative_num_steps` ∈ {{3, 5, 8}}. EAGLE/EAGLE3 require a real HuggingFace \
  `speculative_draft_model`; NEXTN can run without one. A single slow speculative run is \
  NOT a verdict — vary algorithm AND num_steps before abandoning the family. Engine no \
  longer auto-fixes NEXTN-related env vars or mamba-scheduler-strategy — if a config \
  requires them (e.g., SGLANG_ENABLE_SPEC_V2=1, --mamba-scheduler-strategy), set them \
  via extra_env / extra_engine_args yourself.

Leave vLLM-specific fields at defaults: gpu_memory_utilization=0.9, \
max_num_seqs=null, max_num_batched_tokens=null, enforce_eager=false.
"""

_BOTH_ENGINES_SECTION = """
## Available Engines: vLLM and SGLang
Choose ONE engine and set only its relevant parameters. Curated CLI flag references \
for both engines are attached below.

### vLLM-only fields
gpu_memory_utilization, max_num_seqs, max_num_batched_tokens, enforce_eager. \
scheduling_policy: ONLY "fcfs" or "priority". speculative_draft_model required for \
vLLM speculative decoding.

### SGLang-only fields
mem_fraction_static, max_running_requests, max_prefill_tokens, chunked_prefill_size, \
num_continuous_decode_steps, dp_size. scheduling_policy: "fcfs" or "lpm".

Set ONLY the parameters for your chosen engine. Leave the other engine's fields at defaults.
"""

_PROMPT_FOOTER = """
## extra_engine_args vs extra_env — DO NOT CONFUSE THEM
- `extra_engine_args: list[str]` — engine CLI flags that have no dedicated \
  field in this schema. Each list element is one CLI token, e.g. \
  `["--mamba-scheduler-strategy", "extra_buffer"]`. Do NOT duplicate flags the \
  engine manages automatically. Do NOT put `-e KEY=VALUE` tokens here — those \
  are container-runtime flags, not engine flags, and the engine will reject them with \
  `unrecognized arguments`.
- `extra_env: dict[str, str]` — environment variables for the container. ALWAYS \
  use this field for env vars (e.g. `VLLM_FLASH_ATTN_VERSION`, \
  `OMP_NUM_THREADS`, `NCCL_CUMEM_ENABLE`, `CUDA_DISABLE_CONTROL`, \
  `SGLANG_ENABLE_SPEC_V2`). Format: `{{"VAR": "value"}}`. This is an open \
  dictionary — arbitrary keys are accepted; the schema does not constrain \
  key names. NEVER pass env vars via `extra_engine_args` — that breaks \
  argparse and crashes startup.
- For optional fields with no value, emit JSON `null`, not the string `"null"` \
  or empty string `""`. Empty/quoted-empty strings are treated as `null` \
  defensively, but emitting `null` directly is cleaner.

## `failed_phases` in history entries — read this before choosing knobs
Each history entry may include `failed_phases: list`. Each item names a \
benchmark phase (phase_id, workload, concurrency, prompt_length) that \
breached the error-rate gate, along with `error_rate` and a `sample_error` \
string (timeout text, HTTP code, etc.). Headline `peak_throughput` / \
`ttft_p95` are computed from surviving phases ONLY, so they can look fine \
while an entire workload (e.g. `agentic_long_context`) is broken. Rules:
- When the SAME workload's failed_phases appear across multiple consecutive \
  history entries with similar sample_error (e.g. "Session timeout after \
  60s"), the cause is configuration- or workload-level, not the engine knob \
  you're sweeping. Do NOT keep iterating engine flags hoping it fixes itself.
- The failed workload is not what you optimize — your planner_hint and \
  rationale should NAME the chronic failure and either propose a different \
  knob class (e.g. raise per-turn timeout, lower agentic concurrency) or \
  acknowledge that the failure is out of your control (config-side).
- A 100% error_rate at every probed concurrency for the same workload is \
  NOT a "ceiling reached" signal — it's a malfunction. A true ceiling looks \
  like rising error_rate / TTFT across the sweep, not flat 100% everywhere.

## `agentic` block in history entries — read this for ceiling info
History entries may include `agentic: {{max_viable_concurrency, probed, \
viable, ceiling_probed}}`. This is the result of the agentic_long_context \
sweep: a deliberate ceiling probe to measure how many concurrent code-agent \
sessions this config can serve while meeting the agentic SLO. The fields:
- `probed` — concurrencies actually tested in this run.
- `viable` — those that passed (error_rate gate + TTFT p95 SLO + E2E p95 SLO).
- `ceiling_probed` — those that exceeded SLO with timeout-shaped errors. \
  These are NOT bugs and are NOT in `failed_phases`; they are the natural \
  upper end of the sweep.
- `max_viable_concurrency` — headline number: how many parallel agents the \
  config sustained while honoring SLO.
Reading rule: a config with higher `max_viable_concurrency` serves more \
parallel agents under SLO — relevant when the goal cares about agentic \
throughput. A value of 0 with non-empty `ceiling_probed` means the lowest \
probed concurrency already exceeded SLO; the ceiling is BELOW your probe \
range (config-side: lower agentic_concurrency_levels or relax SLO).
{user_instructions}
Generate the next experiment configuration.
"""


def _format_baseline_block(
    baseline: ExperimentSummary | None,
    max_params_per_step: int = 1,
) -> str:
    """Render the measured-baseline anchor block for the planner prompt.

    Empty string when no baseline has been measured yet (the agent then plans
    every experiment from scratch as before). When present, the planner is told
    to iterate ON these exact numbers — change at most `max_params_per_step`
    parameters per experiment and justify the expected impact relative to the
    baseline.
    """
    if baseline is None:
        return ""

    digest = json.dumps(baseline.config_digest, indent=2)
    cmd = baseline.container_command or "(command not recorded)"
    return (
        "\n## BASELINE — operator anchor (MEASURED, experiment {bid})\n"
        "This is the operator-defined reference configuration, run through the "
        "SAME benchmark harness. It is the config you must IMPROVE UPON. Treat "
        "it as the origin of your search, not a generic default.\n\n"
        "### Baseline launch command (exact)\n"
        "```\n{cmd}\n```\n\n"
        "### Baseline config digest\n"
        "```json\n{digest}\n```\n\n"
        "### Baseline measured metrics\n"
        "- engine: {engine}\n"
        "- max_viable_agents (PRIMARY): {max_agents}\n"
        "- agentic_tpot_p95: {agentic_tpot:.1f} ms\n"
        "- agentic_ttft_p95: {agentic_ttft:.1f} ms\n"
        "- agentic_peak_throughput: {agentic_tp:.1f} tok/s\n"
        "- cold-start TTFT p95 (c=1): {ttft:.1f} ms\n"
        "- raw peak throughput (info): {peak_tp:.1f} tok/s\n"
        "- correctness gate passed: {gate}\n\n"
        "### How to use the baseline\n"
        "- START from the baseline's exact flags. Change AT MOST {max_params} "
        "parameter(s) per experiment and NAME, in your rationale, each change "
        "plus its expected impact vs baseline (e.g. 'raise "
        "gpu_memory_utilization 0.88→0.92 to add KV budget → more parallel "
        "agents').\n"
        "- NEVER silently drop a baseline flag that the model needs to stay "
        "correct (tool-call parser, reasoning parser, trust-remote-code, "
        "generation-config overrides). Removing them is a regression, not an "
        "optimization.\n"
        "- If you beat the baseline on the PRIMARY metric (max_viable_agents) "
        "without breaking the correctness gate, that is a win worth building "
        "on; if you fall below it, revert toward the baseline and try a "
        "different single knob.\n"
    ).format(
        bid=baseline.experiment_id,
        max_params=max_params_per_step,
        cmd=cmd,
        digest=digest,
        engine=baseline.engine.value,
        max_agents=baseline.agentic_max_viable_concurrency,
        agentic_tpot=baseline.agentic_tpot_p95,
        agentic_ttft=baseline.agentic_ttft_p95,
        agentic_tp=baseline.agentic_peak_throughput,
        ttft=baseline.low_concurrency_ttft_p95,
        peak_tp=baseline.peak_throughput,
        gate=baseline.correctness_gate_passed,
    )


def _aggregate_failure_patterns(history: list[ExperimentSummary]) -> str:
    """Aggregate failure patterns from history into a concise summary for the LLM.

    Groups failures by classification and engine, showing the planner
    what config classes to avoid.
    """
    if not history:
        return ""

    failed = [h for h in history if h.status.value in ("failed", "failed_correctness", "partial")]
    if not failed:
        return ""

    # Group by (failure_classification, engine)
    pattern_counts: dict[tuple[str, str], int] = {}
    pattern_examples: dict[tuple[str, str], str] = {}
    for h in failed:
        fc = h.failure_classification or "unknown"
        key = (fc, h.engine.value)
        pattern_counts[key] = pattern_counts.get(key, 0) + 1
        if key not in pattern_examples and h.error:
            pattern_examples[key] = h.error[:150]

    # Also count correctness failures
    correctness_failed = [h for h in history if h.status.value == "failed_correctness"]
    if correctness_failed:
        engines_failed_correctness = set(h.engine.value for h in correctness_failed)
        for eng in engines_failed_correctness:
            count = sum(1 for h in correctness_failed if h.engine.value == eng)
            key = ("correctness_failure", eng)
            if key not in pattern_counts:
                pattern_counts[key] = count

    lines = []
    for (fc, eng), count in sorted(pattern_counts.items(), key=lambda x: -x[1]):
        example = pattern_examples.get((fc, eng), "")
        line = f"- {eng}: {fc} ({count}x)"
        if example:
            line += f" — e.g. {example}"
        lines.append(line)

    return "\n".join(lines)


_CONTEXT_BUCKETS = (16384, 32768, 65536, 131072, 262144)


def _estimate_safe_context(hardware: HardwareProfile) -> int:
    """Estimate a safe max_model_len for fallback when the LLM planner fails.

    Returns the largest value from _CONTEXT_BUCKETS that plausibly fits given
    VRAM minus model weight (with ~10% headroom), capped at the model's
    advertised max context. Floor is 16384.
    """
    if not hardware.gpus:
        return min(32768, hardware.model_max_context)

    total_vram_mb = sum(g.vram_total_mb for g in hardware.gpus)

    if hardware.model_size_params:
        model_weight_mb = hardware.model_size_params * 2 / (1024 * 1024)
    else:
        model_weight_mb = total_vram_mb * 0.5

    available_mb = max(0, (total_vram_mb - model_weight_mb) * 0.9)

    # Rough KV-bytes-per-token. Real value depends on n_layers * n_kv_heads *
    # head_dim * 2 (bf16) which we don't always have here, so use a conservative
    # 2 KB/token. The fallback is meant to be safe, not optimal — the LLM
    # planner is expected to pick aggressively from the prompt's bucket list.
    kb_per_token = 2.0
    estimated_ctx_tokens = int(available_mb * 1024 / kb_per_token)

    cap = hardware.model_max_context
    eligible = [b for b in _CONTEXT_BUCKETS if b <= cap and b <= estimated_ctx_tokens]
    if eligible:
        return max(eligible)

    # Nothing in the bucket list fits — fall back to the smallest bucket
    # capped at the model's max context (rounded down).
    return min(_CONTEXT_BUCKETS[0], cap) if cap >= 4096 else max(cap, 4096)


def _get_forced_engine(
    history: list[ExperimentSummary],
    available: list[EngineType],
) -> EngineType | None:
    """Force engine switch if last 2 experiments used the same engine."""
    if len(available) < 2 or len(history) < 2:
        return None
    last_engines = [h.engine for h in history[-2:]]
    if len(set(last_engines)) == 1:
        current = last_engines[0]
        other = [e for e in available if e != current]
        if other:
            return other[0]
    return None


def _should_disable_speculative(
    history: list[ExperimentSummary],
    engine: EngineType,
    threshold: int = 3,
) -> bool:
    """Disable speculative decoding if last N experiments with this engine all failed."""
    engine_history = [h for h in history if h.engine == engine]
    if len(engine_history) < threshold:
        return False
    recent = engine_history[-threshold:]
    return all(h.status.value == "failed" for h in recent)


def _get_quarantined_engines(
    history: list[ExperimentSummary],
    threshold: int = 3,
    loaded_top_history: list[ExperimentSummary] | None = None,
) -> set[EngineType]:
    """Park engines that have NEVER produced a success and keep failing.

    Quarantine fires only when an engine has zero successes (across the current
    session AND `loaded_top_history` from the DB for matching hardware/model)
    AND has accumulated `threshold` or more failures in the current session.
    This protects against the "fundamental engine/model incompatibility" case
    (repeated startup_crash, argparse_error, OOM) where burning more budget is
    wasteful — without locking out an engine that owns the leaderboard just
    because the planner queued up a few risky configs in a row. Restart with a
    different image to lift a quarantine that has fired.

    Why both histories: if an engine had successes in prior sessions (loaded
    from DB), those successes are evidence the engine works on this exact
    hardware/model, so a streak of failures in the current session is a tuning
    problem the planner should iterate on, not a quarantine signal.
    """
    successes: set[EngineType] = set()
    for h in history:
        if h.status.value == "success":
            successes.add(h.engine)
    for h in loaded_top_history or []:
        if h.status.value == "success":
            successes.add(h.engine)
    failures: dict[EngineType, int] = {}
    for h in history:
        if h.status.value != "success":
            failures[h.engine] = failures.get(h.engine, 0) + 1
    return {
        e for e, c in failures.items()
        if c >= threshold and e not in successes
    }


def _summary_to_prompt_entry(h: ExperimentSummary) -> dict:
    """Compact dict view of a summary for the LLM prompt."""
    entry: dict = {
        "id": h.experiment_id,
        "engine": h.engine.value,
        "status": h.status.value,
        "config": h.config_digest,
        "container_command": h.container_command,
        "rationale": h.rationale,
        "peak_throughput": h.peak_throughput,
        "ttft_p95": h.low_concurrency_ttft_p95,
        "tpot_p95": h.low_concurrency_tpot_p95,
        "smoke_pass": f"{h.smoke_tests_passed}/{h.smoke_tests_total}",
        "correctness_gate": h.correctness_gate_passed,
        "classification": h.optimization_classification.value,
    }
    if h.error:
        entry["error"] = h.error
    if h.failure_classification:
        entry["failure_type"] = h.failure_classification
    # Per-phase failure detail (structured, not buried in the error string).
    # Crucial for spotting systemic patterns like "agentic phase fails 100%
    # in every recent experiment" that headline metrics hide.
    if h.failed_phases:
        entry["failed_phases"] = [
            {
                "phase": fp.phase_id,
                "workload": fp.workload_id,
                "concurrency": fp.concurrency,
                "prompt_length": fp.prompt_length,
                "error_rate": round(fp.error_rate, 3),
                "sample_error": fp.error_sample,
            }
            for fp in h.failed_phases
        ]
    # Agentic ceiling-probe sweep: NOT a failure signal. Tells the planner
    # how many parallel agents this config served while meeting SLO, and at
    # which concurrencies it ran out of room. Empty when no agentic phases
    # ran (small max_model_len, or enable_agentic_long_context=false).
    if h.agentic_concurrencies_probed:
        entry["agentic"] = {
            "max_viable_concurrency": h.agentic_max_viable_concurrency,
            "probed": h.agentic_concurrencies_probed,
            "viable": h.agentic_concurrencies_viable,
            "ceiling_probed": h.agentic_concurrencies_ceiling,
        }
    if h.llm_commentary:
        entry["analysis"] = h.llm_commentary
    return entry


async def planner_node(state: AgentState) -> dict:
    """Use LLM to select the next experiment configuration."""
    config = state["config"]
    hardware = state["hardware"]
    history = state.get("experiment_history", [])
    loaded_top_history = state.get("loaded_top_history", [])
    goal = state.get("next_optimization_goal", OptimizationGoal.EXPLORE)

    # Format history for LLM (last 15 experiments).
    # Validation failures are stored compactly: full config/container_command/rationale
    # would just balloon the prompt without teaching the LLM anything beyond
    # "fields-of-the-other-engine were populated", which the sanitizer in
    # _build_experiment_config now prevents structurally.
    history_for_llm = []
    for h in history[-15:]:
        if (h.failure_classification or "") == "validation":
            history_for_llm.append({
                "id": h.experiment_id,
                "engine": h.engine.value,
                "status": "failed_validation",
                "error": (h.error or "")[:200],
            })
            continue
        history_for_llm.append(_summary_to_prompt_entry(h))

    # Top results from prior runs on the same hardware/model. These come from
    # `history_loader` and are already filtered to status in {success, partial}
    # with valid metrics, so we don't re-filter here.
    loaded_top_for_llm = [_summary_to_prompt_entry(h) for h in loaded_top_history]

    # Engine quarantine: if an engine has produced zero successes (this session
    # OR in loaded_top_history from the DB for matching hardware/model) AND has
    # racked up >=3 failures this session, exclude it from the planner's
    # choices. An engine with any prior success on this stack is never
    # quarantined — repeated failures there are a tuning signal, not an
    # incompatibility signal. Falls back to all available engines only if
    # quarantine would leave nothing to pick.
    quarantined = _get_quarantined_engines(history, loaded_top_history=loaded_top_history)
    effective_engines = [e for e in hardware.available_engines if e not in quarantined]
    if quarantined:
        logger.warning(
            "Engine quarantine active: %s (>=3 failures, zero successes this "
            "session or in loaded history). Restart with a different image tag "
            "to lift.",
            ", ".join(sorted(e.value for e in quarantined)),
        )
    if not effective_engines:
        logger.warning(
            "All engines quarantined — falling back to original list. "
            "Stop the agent and fix engine images before continuing."
        )
        effective_engines = list(hardware.available_engines)

    # Determine if we need to force a specific engine (alternation rule)
    forced_engine = _get_forced_engine(history, effective_engines)
    if forced_engine:
        logger.info("Forcing engine=%s (alternation rule)", forced_engine.value)

    # Check if speculative decoding should be disabled for each engine
    spec_disabled: dict[EngineType, bool] = {}
    for eng in effective_engines:
        spec_disabled[eng] = _should_disable_speculative(history, eng)
        if spec_disabled[eng]:
            logger.info(
                "Auto-disabling speculative decoding for %s (last 3 experiments failed)",
                eng.value,
            )

    # Build engine-specific prompt section + load curated CLI-flag references
    # for the engine(s) the planner can use this turn (minimizes prompt size
    # when an engine is forced).
    if forced_engine == EngineType.VLLM:
        engine_section = _VLLM_SECTION
        engine_instruction = "You MUST use **vLLM** for this experiment."
        engine_docs_to_inject = [EngineType.VLLM]
    elif forced_engine == EngineType.SGLANG:
        engine_section = _SGLANG_SECTION
        engine_instruction = "You MUST use **SGLang** for this experiment."
        engine_docs_to_inject = [EngineType.SGLANG]
    else:
        engine_section = _BOTH_ENGINES_SECTION
        engine_instruction = f"Choose from: {', '.join(e.value for e in effective_engines)}"
        engine_docs_to_inject = list(effective_engines)

    docs_blocks: list[str] = []
    for eng in engine_docs_to_inject:
        doc_text = _load_curated_docs(eng)
        if doc_text:
            docs_blocks.append(doc_text)
    engine_docs_block = "\n\n".join(docs_blocks)

    # Aggregate failure patterns for the LLM
    failure_patterns = _aggregate_failure_patterns(history)

    user_instructions = ""
    if config.planner_instructions:
        user_instructions = f"\n## User Instructions\n{config.planner_instructions}\n"

    # Baseline anchor: prefer the explicit baseline_summary (from history_loader
    # / this session's measured baseline); fall back to scanning session history
    # for the is_baseline entry in case state was reconstructed.
    baseline_summary = state.get("baseline_summary")
    if baseline_summary is None:
        for h in history:
            if getattr(h, "is_baseline", False):
                baseline_summary = h
                break
    max_params_per_step = config.experiments.max_params_per_step
    baseline_block = _format_baseline_block(baseline_summary, max_params_per_step)

    prompt = _PROMPT_HEADER.format(
        hardware_json=hardware.model_dump_json(indent=2),
        engine_instruction=engine_instruction,
        optimization_goal=goal.value,
        max_params_per_step=max_params_per_step,
        baseline_block=baseline_block,
        history_json=json.dumps(history_for_llm, indent=2) if history_for_llm else "No experiments yet.",
        loaded_top_history_json=(
            json.dumps(loaded_top_for_llm, indent=2)
            if loaded_top_for_llm
            else "No prior runs on this hardware/model."
        ),
        best_agentic_c=state.get("best_agentic_max_viable_c", 0),
        best_agentic_id=state.get("best_agentic_config_id", "none"),
        best_agentic_tpot=state.get("best_agentic_tpot_p95", float("inf")),
        best_agentic_tp=state.get("best_agentic_throughput", 0.0),
        best_throughput=state.get("best_throughput", 0),
        best_throughput_id=state.get("best_throughput_config_id", "none"),
        best_latency=state.get("best_latency_ttft_p95", float("inf")),
        best_latency_id=state.get("best_latency_config_id", "none"),
        best_balanced_tp=state.get("best_balanced_throughput", 0),
        best_balanced_lat=state.get("best_balanced_latency", float("inf")),
        best_balanced_id=state.get("best_balanced_config_id", "none"),
        exp_count=state.get("experiments_count", 0),
        max_experiments=config.experiments.max_experiments,
        latency_threshold=config.benchmark.latency_threshold_ms,
        model_max_context=hardware.model_max_context,
        gpu_count=hardware.gpu_count,
        fixed_quantization=config.quantization or "disabled (no quantization)",
        fixed_max_model_len=(
            f"{config.max_model_len} (LLM cannot vary it)"
            if config.max_model_len is not None
            else "not fixed — pick per Rule 9 below"
        ),
    ) + engine_section

    if failure_patterns:
        prompt += f"\n## Known Failure Patterns\n{failure_patterns}\n"

    if engine_docs_block:
        prompt += f"\n{engine_docs_block}\n"

    prompt += _PROMPT_FOOTER.format(user_instructions=user_instructions)

    logger.info("Asking LLM to plan experiment #%d...", state.get("experiments_count", 0) + 1)

    full_prompt = prompt + "\n\nGenerate the next experiment configuration."

    try:
        result: PlannerOutput = await structured_output(
            full_prompt, PlannerOutput, config.agent_llm
        )
    except Exception as e:
        error_summary = str(e).split("\n")[0][:200]
        logger.error("LLM structured output failed, using fallback: %s", error_summary)
        safe_ctx = _estimate_safe_context(hardware)
        result = PlannerOutput(
            engine=effective_engines[0].value if effective_engines else "vllm",
            tensor_parallel_size=hardware.gpu_count,
            max_model_len=safe_ctx,
            rationale=f"Fallback: LLM failed — {error_summary}",
        )

    # Override engine if alternation rule requires it
    if forced_engine:
        result.engine = forced_engine.value

    # Convert PlannerOutput to ExperimentConfig with validation
    resolved_engine = EngineType.VLLM if "vllm" in result.engine.lower() else EngineType.SGLANG
    if spec_disabled.get(resolved_engine, False):
        if result.speculative_algorithm:
            logger.info(
                "Stripping speculative_algorithm=%s (auto-disabled for %s)",
                result.speculative_algorithm, resolved_engine.value,
            )
            result.speculative_algorithm = None
            result.speculative_draft_model = None
            result.speculative_num_steps = None
    experiment = _build_experiment_config(result, hardware, config)

    logger.info(
        "Planned: %s, TP=%d, ctx=%s, quant=%s, rationale: %s",
        experiment.engine.value,
        experiment.tensor_parallel_size,
        experiment.max_model_len,
        experiment.quantization or "none",
        experiment.rationale,
    )

    return {"current_config": experiment}


def _zero_to_none(value: int | float | None) -> int | float | None:
    """Treat sentinel 0/0.0 as None for optional numeric fields.

    Strict json_schema mode forces every field to be present, and some LLM
    providers emit 0 instead of null for `int | None` / `float | None`.
    Validator and engine builders rely on None to mean "not set".
    """
    if value is None:
        return None
    if value == 0:
        return None
    return value


_SENTINEL_STRINGS = {"null", "none", "nil", "n/a", "na", "undefined", ""}


def _strip_wrapping_quotes(s: str) -> str:
    """Strip a matched pair of leading/trailing quotes (`"foo"`, `'foo'`).

    The LLM occasionally emits `'""'` for "no value" — two literal quote
    characters as the field value. Without unwrapping, sentinel detection
    sees a non-empty string and lets it through; the engine then tries to
    download a HF repo literally named `""` and crashes.
    """
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        return s[1:-1]
    return s


def _str_to_none(s: str | None) -> str | None:
    """Treat sentinel string values like 'null' / 'none' / '' as None.

    Strict json_schema clients sometimes serialize JSON null as the literal
    string "null" for `str | None` fields. Engine builders pass these through
    to nerdctl run, producing invalid CLI flags like `--quantization null`.
    """
    if s is None:
        return None
    cleaned = _strip_wrapping_quotes(s.strip())
    if cleaned.strip().lower() in _SENTINEL_STRINGS:
        return None
    s = cleaned
    return s


def _str_with_default(s: str | None, default: str) -> str:
    """Same as _str_to_none but returns a default for required string fields."""
    cleaned = _str_to_none(s)
    return cleaned if cleaned is not None else default


def _lift_env_tokens_from_engine_args(
    args: list[str],
    extra_env: dict[str, str],
) -> list[str]:
    """Move `-e KEY=VALUE` / `--env KEY=VALUE` tokens out of engine args.

    The LLM occasionally smuggles container-runtime env tokens through
    `extra_engine_args` when it can't (or thinks it can't) fill `extra_env`.
    Those tokens land AFTER the image name in `nerdctl run` and become argv
    to the engine binary, which rejects them with `unrecognized arguments`.
    Detect and re-route to `extra_env`; existing keys win (don't clobber what
    the LLM already put in `extra_env`).
    """
    out: list[str] = []
    i = 0
    while i < len(args):
        tok = args[i]
        # `-e KEY=VALUE` or `--env KEY=VALUE` (two-token form)
        if tok in ("-e", "--env") and i + 1 < len(args) and "=" in args[i + 1]:
            key, _, val = args[i + 1].partition("=")
            extra_env.setdefault(key, val)
            i += 2
            continue
        # `-e=KEY=VALUE` / `--env=KEY=VALUE` (single-token form, rarer)
        for prefix in ("-e=", "--env="):
            if tok.startswith(prefix):
                payload = tok[len(prefix):]
                if "=" in payload:
                    key, _, val = payload.partition("=")
                    extra_env.setdefault(key, val)
                    i += 1
                    break
        else:
            out.append(tok)
            i += 1
            continue
        # ran the for-else's break — token consumed, continue loop
    return out


def _strip_flag(args: list[str], flag: str) -> list[str]:
    """Remove `flag` and its immediate value from a CLI tokens list.

    Handles both `--foo value` and `--foo=value` forms. Used to enforce that
    knobs the agent fixes at run level (e.g. --quantization) cannot leak
    through extra_engine_args.
    """
    out: list[str] = []
    skip_next = False
    prefix_eq = f"{flag}="
    for tok in args:
        if skip_next:
            skip_next = False
            continue
        if tok == flag:
            skip_next = True
            continue
        if tok.startswith(prefix_eq):
            continue
        out.append(tok)
    return out


def _build_experiment_config(
    output: PlannerOutput,
    hardware: HardwareProfile,
    config: AgentConfig,
) -> ExperimentConfig:
    """Convert validated PlannerOutput to ExperimentConfig with safety checks.

    Cross-engine fields are stripped here based on the resolved engine, so the
    LLM cannot fail validation by populating fields that belong to the other
    engine (a recurring failure mode with strict json_schema clients that emit
    0/null inconsistently).
    """
    # Normalize engine
    engine_str = output.engine.lower()
    engine = EngineType.VLLM if "vllm" in engine_str else EngineType.SGLANG

    # Validate TP size
    tp = output.tensor_parallel_size
    if tp > hardware.gpu_count:
        tp = hardware.gpu_count
    if hardware.gpu_count > 0 and hardware.gpu_count % tp != 0:
        valid_tps = [i for i in range(1, hardware.gpu_count + 1) if hardware.gpu_count % i == 0]
        tp = min(valid_tps, key=lambda x: abs(x - tp))

    # max_model_len: when fixed at AgentConfig level, the LLM choice is
    # ignored — operator-level invariant for the whole run. Otherwise validate
    # and cap to the model's advertised max.
    if config.max_model_len is not None:
        max_model_len = config.max_model_len
    else:
        max_model_len = output.max_model_len
    if max_model_len > hardware.model_max_context:
        max_model_len = hardware.model_max_context
    # Sanity: at least 512
    max_model_len = max(max_model_len, 512)

    # Validate scheduling_policy per engine (also normalize 'null' sentinel)
    scheduling_policy = _str_with_default(output.scheduling_policy, "fcfs")
    if engine == EngineType.VLLM and scheduling_policy not in ("fcfs", "priority"):
        scheduling_policy = "fcfs"
    elif engine == EngineType.SGLANG and scheduling_policy not in ("fcfs", "lpm"):
        scheduling_policy = "fcfs"

    # Normalize 0-as-sentinel to None for optional numeric fields
    mem_fraction_static = _zero_to_none(output.mem_fraction_static)
    max_num_seqs = _zero_to_none(output.max_num_seqs)
    max_running_requests = _zero_to_none(output.max_running_requests)
    max_num_batched_tokens = _zero_to_none(output.max_num_batched_tokens)
    max_prefill_tokens = _zero_to_none(output.max_prefill_tokens)
    chunked_prefill_size = _zero_to_none(output.chunked_prefill_size)
    speculative_num_steps = _zero_to_none(output.speculative_num_steps)
    dp_size = _zero_to_none(output.dp_size)

    # Quantization is fixed at run level — same value for every experiment.
    # The LLM no longer chooses it, so we read straight from AgentConfig.
    quantization = _str_to_none(config.quantization)

    # Normalize 'null'/'none'/'' sentinel strings to None for optional string fields.
    # Without this, engine builders emit invalid CLI like `--attention-backend null`
    # which vLLM/SGLang argparse rejects with `invalid choice: 'null'`.
    attention_backend = _str_to_none(output.attention_backend)
    speculative_algorithm = _str_to_none(output.speculative_algorithm)
    speculative_draft_model = _str_to_none(output.speculative_draft_model)
    # Required strings with safe defaults — if LLM emits 'null', fall back.
    dtype = _str_with_default(output.dtype, "auto")
    kv_cache_dtype = _str_with_default(output.kv_cache_dtype, "auto")

    # Strip cross-engine fields based on resolved engine
    if engine == EngineType.VLLM:
        mem_fraction_static = None
        max_running_requests = None
        max_prefill_tokens = None
        chunked_prefill_size = None
        num_continuous_decode_steps = 1
        dp_size = None
    else:  # SGLang
        max_num_seqs = None
        max_num_batched_tokens = None
        # vLLM's gpu_memory_utilization is ignored for SGLang at the engine
        # builder level, but normalize at config level to keep digests clean.
        num_continuous_decode_steps = output.num_continuous_decode_steps or 1

    # Inherit the operator baseline's container env as the BASE layer so planned
    # configs don't silently drop the baseline's NCCL/OMP/CUDA tuning (which
    # would make baseline-vs-agent comparisons unfair — perf deltas could come
    # from missing env rather than engine knobs). The LLM's own extra_env wins
    # per-key, so the planner can still deliberately override a specific var.
    baseline_env: dict[str, str] = {}
    if config.baseline is not None:
        baseline_env = dict(config.baseline.extra_env)
    extra_env = {**baseline_env, **dict(output.extra_env)}
    if engine == EngineType.VLLM:
        for k in list(extra_env.keys()):
            if k.startswith("SGLANG"):
                extra_env.pop(k)

    # Defense-in-depth: quantization is fixed by AgentConfig, so an LLM-supplied
    # `--quantization X` in extra_engine_args would silently override the run
    # setting (and dedup_flags can't tell which value to keep). Strip both the
    # flag and its value before they reach the engine builder.
    extra_engine_args = _strip_flag(output.extra_engine_args, "--quantization")
    # Same defense for engine flags that have dedicated fields in this schema:
    # if the LLM duplicates them in extra_engine_args, we'd emit conflicting
    # tokens (and dedup_flags keeps the first occurrence — unstable wrt order).
    for dup_flag in (
        "--speculative-draft-model-path",
        "--speculative-draft-model",
        "--speculative-algorithm",
        "--speculative-num-steps",
        "--max-model-len",
        "--context-length",
        "--tensor-parallel-size",
        "--tp-size",
    ):
        extra_engine_args = _strip_flag(extra_engine_args, dup_flag)
    # Sanitize: relocate misrouted `-e KEY=VALUE` tokens (which would otherwise
    # become argv to the engine binary, not container env) into `extra_env`.
    extra_engine_args = _lift_env_tokens_from_engine_args(extra_engine_args, extra_env)

    return ExperimentConfig(
        engine=engine,
        tensor_parallel_size=tp,
        pipeline_parallel_size=output.pipeline_parallel_size,
        data_parallel_size=output.data_parallel_size,
        max_model_len=max_model_len,
        gpu_memory_utilization=output.gpu_memory_utilization,
        mem_fraction_static=mem_fraction_static,
        max_num_seqs=max_num_seqs,
        max_running_requests=max_running_requests,
        max_num_batched_tokens=max_num_batched_tokens,
        max_prefill_tokens=max_prefill_tokens,
        scheduling_policy=scheduling_policy,
        quantization=quantization,
        dtype=dtype,
        kv_cache_dtype=kv_cache_dtype,
        enable_chunked_prefill=output.enable_chunked_prefill,
        chunked_prefill_size=chunked_prefill_size,
        enable_prefix_caching=output.enable_prefix_caching,
        enforce_eager=output.enforce_eager,
        attention_backend=attention_backend,
        speculative_algorithm=speculative_algorithm,
        speculative_draft_model=speculative_draft_model,
        speculative_num_steps=speculative_num_steps,
        num_continuous_decode_steps=num_continuous_decode_steps,
        dp_size=dp_size,
        extra_engine_args=extra_engine_args,
        extra_env=extra_env,
        rationale=output.rationale,
    )
